#pragma once
// Local FormIDs (in Frostfall.esp) of the globals Frostfall.dll reads. Generated by tools/esl_step4_dll.py.
// The ESL build (cmake -DFROSTFALL_ESL=ON) uses the compacted FormIDs of the ESL Frostfall.esp.

namespace ids
{
#ifdef FROSTFALL_ESL
	inline constexpr unsigned int FrostfallRunning = 0x000A9A;  // was 0x06DCFB
	inline constexpr unsigned int Frost_AttributeExposureMeter = 0x000B96;  // was 0x08827A
	inline constexpr unsigned int Frost_AttributeExposureMax = 0x000AE7;  // was 0x07CAA4
	inline constexpr unsigned int Frost_AttributeWetness = 0x000A00;  // was 0x06458C
	inline constexpr unsigned int Frost_AttributeWetnessMax = 0x000AE8;  // was 0x07CAA5
	inline constexpr unsigned int Frost_AttributeMeterTempLevel = 0x000AEA;  // was 0x07CAA7
	inline constexpr unsigned int Frost_AttributeMeterTempLevelMax = 0x000AEB;  // was 0x07CAA8
	inline constexpr unsigned int Frost_AttributeWarmth = 0x000A27;  // was 0x067B8F
	inline constexpr unsigned int Frost_Calc_MaxWarmth = 0x000A44;  // was 0x068110
	inline constexpr unsigned int Frost_AttributeCoverage = 0x000A29;  // was 0x067B91
	inline constexpr unsigned int Frost_Calc_MaxCoverage = 0x000A45;  // was 0x068111
	inline constexpr unsigned int Frost_Setting_MeterDisplayMode = 0x000985;  // was 0x05CE05
#else
	inline constexpr unsigned int FrostfallRunning = 0x06DCFB;
	inline constexpr unsigned int Frost_AttributeExposureMeter = 0x08827A;
	inline constexpr unsigned int Frost_AttributeExposureMax = 0x07CAA4;
	inline constexpr unsigned int Frost_AttributeWetness = 0x06458C;
	inline constexpr unsigned int Frost_AttributeWetnessMax = 0x07CAA5;
	inline constexpr unsigned int Frost_AttributeMeterTempLevel = 0x07CAA7;
	inline constexpr unsigned int Frost_AttributeMeterTempLevelMax = 0x07CAA8;
	inline constexpr unsigned int Frost_AttributeWarmth = 0x067B8F;
	inline constexpr unsigned int Frost_Calc_MaxWarmth = 0x068110;
	inline constexpr unsigned int Frost_AttributeCoverage = 0x067B91;
	inline constexpr unsigned int Frost_Calc_MaxCoverage = 0x068111;
	inline constexpr unsigned int Frost_Setting_MeterDisplayMode = 0x05CE05;
#endif
}
